### ISSUE TITLE
i get this error every time it snipes a code

### ISSUE THREAD

**Issue by JacksonTheProgrammer** [yafyz/nitrsnip#11]
my account is fully verified with a phone number and an email but every time it snipes a code i get this message under the Response tab

{"message": "You need to verify your account in order to perform this action.", "code": 40002}

**Comment by yafyz** [comment]
this happens when your account gets locked until you phone verify
though if you are saying that your account is verified and everything then uh idk
you can try updating the token if that changes anything

**Comment by JacksonTheProgrammer** [comment]
I updated the token and when it sniped 2 codes it still got that message

**Comment by JacksonTheProgrammer** [comment]
i think discord has made that api for bots only

**Comment by yafyz** [comment]
i dont think a code claim api would even be enabled for bot accounts

**Comment by JacksonTheProgrammer** [comment]
well i read somewhere that the api is blocked for users

**Comment by JacksonTheProgrammer** [comment]
can u test it to see if it works for u?

**Comment by yafyz** [comment]
attempting to claim a code through the api seems to work
dont have a valid code to test on but it returns that the code is invalid

**Comment by JacksonTheProgrammer** [comment]
is heroku the issue or because I am using my alt to snipe for my main?

**Comment by JacksonTheProgrammer** [comment]
u can test with an invalid code btw

**Comment by JacksonTheProgrammer** [comment]
I fixed it by using an old version of the snipe bot that was posted 1 year ago

**Comment by yafyz** [comment]
how old

**Comment by JacksonTheProgrammer** [comment]
"that was posted 1 year ago"

**Comment by JacksonTheProgrammer** [comment]
I was using replit for it btw

**Comment by JacksonTheProgrammer** [comment]
heroku works on the newest version

**Comment by yafyz** [comment]
i meant exact commit
