### ISSUE TITLE
where can i see tokens.txt tokens being loaded ?

### ISSUE THREAD

**Issue by p00rprogrammer** [yafyz/nitrsnip#12]
Its a really good bot. Sniped twice classics on my alts.
But while testing the script in vscode, i couldnt find anywhere where the bot would login to my tokens in tokens.txt .
debugger goes from main.js > client.js > and back. Coudnt see tokens being loaded in debugger too.

Moreover, it only shows creating account for n1.
Recently, i edited the tokens.txt to aisdaijdiadjaisjdiajd;  it does shows that creating account for n1 but how will i know if login was successful ? 
So, if possible could you kindly add the meaning discord dev Gateway Opcodes and the name of user which doesnt logins ?

I am attaching a sample code for Displaying the email (without @yahoo.com) of account  which i tried and did work for n0 (Main Token).

async function getName(token){
    email = null
    request.get({
        url: 'https://discord.com/api/v12/users/@me',
        json: true,
        headers: {
            "Content-Type": "application/json",
            "Authorization": token,
        }
    }, (err, body, res) => {
        if(err)return console.log(err)
        if(body.statusCode == 429){
            console.log(temp)
        }
        else if(body.statusCode == 200){
            let email = res.email
            v = email.split("@");
            temp = v[0];
            console.log(`Account Name: ${temp}`)
        }else{
            temp = "Login Error"
            console.log(temp)
        }
    })
}

**Comment by yafyz** [comment]
the number (ex. n0) corresponds to the line in the text file (zero based, ex. 0 corresponds to line 1)
the tokens are loaded in main.js (line 20-35 loads them from file, line 39-47 creates discord gateway connections)

if the account didnt recieve a heartbeat ack from discord gateway in more than 100 seconds, it will forcefully attempt to reconnect and send a message through error webhook about it
if you get a single message, it probably was just some random connection problem, if it sends every 100 seconds or so, the token is probably invalid

i dont actually like "login" anywhere or check if the tokens are valid, i just attempt to connect to the discord gateway and if discord closes the connection, i just attempt to reconnect

discord gateway opcodes documentation can be found here https://discord.com/developers/docs/topics/opcodes-and-status-codes
