### ISSUE TITLE
Heroku code flagged sadly

### ISSUE THREAD

**Issue by MaiSan9999** [yafyz/nitrsnip#14]
Heroku code flagged sadly

**Comment by yafyz** [comment]
yeah it is, you can prob just fork it

**Comment by MaiSan9999** [comment]
> yeah it is, you can prob just fork it

that's risky i was able to make run u/slow nitro sniper by forking but after months it  got banned
and i tried by creating new account and fork now they instaban
i don't know if this apply for this code too.

**Comment by yafyz** [comment]
uh, welp
maybe manually re-upload it as a private repo, so it doesn't show up as a fork of the original repo, idk
