### ISSUE TITLE
why

### ISSUE THREAD

**Issue by mewzax** [yafyz/nitrsnip#15]
why r u using zlib-sync? for performance?

**Comment by mewzax** [comment]
`wss://gateway.discord.gg/?encoding=etf&v=9&compress=zlib-stream`

I mean why using `&compress=zlib-stream` and zlib-sync in your code ?

**Comment by yafyz** [comment]
well yeah, for performance
compression usually compresses data -> data to be sent is smaller

**Comment by mewzax** [comment]
ok makes sense
