### ISSUE TITLE
Help Please!

### ISSUE THREAD

**Issue by thakuranuj24** [yafyz/nitrsnip#2]
Can you please tell me some servers where actual nitro drops happen, I've seen people sniping nitro under 24 hours because of being in good servers, but if I ask them they never tell me anything, I've had a nitro sniper running for a whole month and tried to join servers which I think had nitro drops but found nothing, I made a sniper myself too :c. It would be a great help If you could give me some servers where I can snipe nitro.

**Comment by yafyz** [comment]
tbh, i would say that servers that advertise themselves as nitro dropping servers are generally fake
i would recommend joining a lot of active community servers instead
