### ISSUE TITLE
Payment source required to redeem gift.

### ISSUE THREAD

**Issue by realdep** [yafyz/nitrsnip#3]
I have a payment method in my account but when the sniped code isn't already redeemed, it says payment required. I tried using a different card but the issue persists. My instance is deployed on heroku.
![Untitled](https://user-images.githubusercontent.com/9782679/125204176-98ad8080-e284-11eb-8d1b-ea5456ef58f9.png)

**Comment by yafyz** [comment]
This is an epic code, not a normal code, they require few extra things to be sent over to get claimed but you can only claim them if you never had nitro, which makes the useless for nitro sniping. + You can get them for free from the epic store.
tl;dr you are not missing out on normal nitro gifts if it says "Payment source required to redeem gift.".
