### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Whitewolf342** [yafyz/nitrsnip#6]
![image](https://user-images.githubusercontent.com/74878033/147420620-2bbb78b6-5d0e-4675-94e8-1d0d8ccfda61.png)
Im getting this error,
Im sorry, I don't know how to use node properly and I know I'm supposed to set it up myself.

**Comment by yafyz** [comment]
did you modify the js file ?? you are not supposed to do that

**Comment by Whitewolf342** [comment]
Nah it's fine now I got it, but it doesn't work anymore it doesn't claim codes from the accounts.

**Comment by yafyz** [comment]
why do you think so

**Comment by Whitewolf342** [comment]
It only claims the codes you drop, and I saw the same issue in a similar one.

**Comment by yafyz** [comment]
got couple reports that the sniper still works, i looked into this months ago and if anything, its some discord thing, you dont (or atleast back then) send anything over to discord saying you clicked into a channel
