### ISSUE TITLE
Feature request - add gaming_only option

### ISSUE THREAD

**Issue by josesilveiraa** [yafyz/nitrsnip#8]
This would be a great addition since there isn't any sniper with this option as of now. it'd help snipers to get more gaming gifts

**Comment by yafyz** [comment]
what exactly is a "gaming gift", those 24 char ones?

**Comment by josesilveiraa** [comment]
the more expensive one

**Comment by yafyz** [comment]
??

**Comment by josesilveiraa** [comment]
The nitro that comes with boosts

**Comment by yafyz** [comment]
cant, you cant tell if its classic or boost nitro just from the code
